#!/usr/bin/env sh

env FORDPATHS="$(dirname $0)/../src/ford/internal/":"$(dirname $0)/../src/ford/" LD_LIBRARY_PATH="$(dirname $0)/../build/" valgrind --tool=massif --massif-out-file="$PWD/$1.massif"  "$(dirname $0)/$1.elf" $2 
